### ISSUE TITLE
安卓提示授权失败了  有空了麻烦看下呢 

### ISSUE THREAD

**Issue by IceTears1** [yangyu92/flu_dingtalk#1]
安卓提示授权失败了  有空了麻烦看下呢

**Comment by yangyu92** [comment]
找时间全面更新一下，版本有点老啦

**Comment by yuyangpl** [comment]
> 安卓提示授权失败了 有空了麻烦看下呢

已经处理啦，可以试试看，当前版本 flu_dingtalk: 1.1.0
