### ISSUE TITLE
跳转到钉钉，回调监听没有数据

### ISSUE THREAD

**Issue by xy98ml** [yangyu92/flu_dingtalk#2]
能成功跳转到钉钉，也可以获取授权，但是在钉钉点击授权，返回app的之后，回调监听没有数据，

**Comment by yangyu92** [comment]
版本很久没有维护啦，找时间全面升级一下

**Comment by xy98ml** [comment]
好的好的！！期待大佬更新！粉丝催更！❤️❤️

**Comment by yuyangpl** [comment]
> 能成功跳转到钉钉，也可以获取授权，但是在钉钉点击授权，返回app的之后，回调监听没有数据，

已经处理啦，可以试试看，当前版本 flu_dingtalk: 1.1.0
